### ISSUE TITLE
Putting the instructions for aligning to reference at start, and add it to the script help output.

### ISSUE THREAD

**Issue by sbridgett** [cov-ert/type_variants#3]
In the instructions on github for using the type_varaints script, I think it would be good to put the point about how to align to the reference at the start of the instructions rather than at the end, as it's an important first step that can be overlooked if put at the end, and also add that to the help information printed by the script.  

```
Making an alignment in Wuhan-Hu-1 coordinates
If you have a consensus fasta file(s) containing sequences that haven't been aligned to Wuhan-Hu-1, you can make an alignment to feed to this python script using minimap2, gofasta and the reference fasta file:

minimap2 -a -x asm5 MN908947.fa unaligned.fasta | gofasta sam toMultiAlign --reference MN908947.fa > aligned.fasta
```

**Comment by benjamincjackson** [comment]
I've made some changes to address this, but I've left the alignment instructions at the end of the README. 

Now if any sequences in `--fasta-in` aren't 29903bp long, the program writes a message to stderr and exits (1).

**Comment by sbridgett** [comment]
Thank you for adding this test, which will definitely help prevent incorrect variant calls due to a frame shift in sequences with an insertion or deletion. 

It's probably rarely happens, but I was thinking if a viral sequence has a base insertion near the start and deletion near the end (or visa-versa), then the overall sequence length will still be 29903bp long, but if the sequence is not first aligned to the reference then the type_variant script won't exit, and will still call a variant incorrectly. I was thinking putting the align instruction at start would reduce this possibility.

**Comment by benjamincjackson** [comment]
Actually if you follow the protocols for making the alignment in the README, the query sequences will always be 29903bp long, because insertions relative to the reference are discarded.

And for calling amino acids, this routine is blind to structural variation (including deletions, even though they represented in the query alignment), so if there are frameshift mutations (either insertions or deletions) in CDS, it either won't see them or won't treat them as meaningful: It will just call the triplet of nucleotides aligned to the codon in Wuhan-Hu-1 as the amino acid.

This is the desired behaviour for this routine because it keeps things simple, but it's not a complete solution to calling variants, for the reasons you outline. I will reopen the issue to remind me to write something in the README to this effect.

**Comment by sbridgett** [comment]
Thank you for reopening this. I appreciate that by following the protocol - aligning to the reference first will discard any insertions. However, I had discovered that if unwittingly run type_variant on the consensus sequence before the alignment step, then a one-base insertion anywhere before position 23010 will result in type_variant calling the "aa:S:E484K" SNP as a "K" (ie. a South African variant of concern, which is being monitored as it reduces effectiveness of vaccines). Whereas after alignment to reference removes the insertion, then it is correctly called as an "E" at that position. Sorry if I'm being a pain by requesting this. I was just tying to make it more fool-proof. And thank you for adding the sequence length check.

**Comment by benjamincjackson** [comment]
I think it's safe to close this now
